### ISSUE TITLE
Dockerized Build Fail - missing system library

### ISSUE THREAD

**Issue by mulloymorrow** [snowflakedb/examples#2]
Using the following dockerized build environment: https://gist.github.com/mulloymorrow/dc530a9ecf60eea0e66d8182ebd1df75
The container is running `Ubuntu 15.04`. 

Code gets packaged up succesfully. However, when testing out lambda function, following error is thrown:
`Unable to import module 'lambda_function': libssl.so.1.0.0: cannot open shared object file: No such file or directory`

**Comment by mulloymorrow** [comment]
If we remove [line 35](https://gist.github.com/mulloymorrow/dc530a9ecf60eea0e66d8182ebd1df75#file-dockerized-build-environment-sh-L35), then we'll fail here: https://github.com/snowflakedb/examples/blob/master/lambda_function/package-lambda-function.sh#L13

**Comment by gregrahn** [comment]
As mentioned in [Installing the Snowflake Connector for Python](https://docs.snowflake.net/manuals/user-guide/python-connector-install.html) one needs to have:
`sudo apt-get install -y libssl-dev libffi-dev`
Then you can also use this as a quick smoke test (add your login info):
```python
import snowflake.connector
cnx = snowflake.connector.connect(user='', password='', account='')
```

**Comment by mulloymorrow** [comment]
The 2nd comment above is the error thrown when following the installation directions. 
The 1st comment describes the issue after `apt-get install -y python-dev`. Installing `python-dev` allows us to get a little further by packaging the lambda function. However, the package cannot be run be AWS Lambda at runtime.

**Comment by mulloymorrow** [comment]
Looks like the root problem is I'm packaging on Ubuntu, not Amazon Linux. Going to use a Docker Container with Amazon Linux and report back.

**Comment by gregrahn** [comment]
I'll assume using Amazon Linux fixed the issue, so closing this.
